name: CI
on:
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3.5.3

    - name: use NodeJs
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    - run: npm ci
    - run: npm run prettier:check
    - run: npm test -- --coverage
      env:
        CI: true
